heavy refactoring for reconcile controllers intialization, task build scripts updated, and resolves issue/56 (#58)

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -33,9 +33,9 @@ tasks:
       - "./**/*.go"
     method: timestamp
 
-  build:
-    cmds:
-      - operator-sdk build harbor.dev.madhouselabs.io/kloudlite/operator:latest
+#  build:
+#    cmds:
+#      - operator-sdk build harbor.dev.madhouselabs.io/kloudlite/operator:latest
 
   deploy:
     env:
@@ -46,6 +46,50 @@ tasks:
       - cd config/manager && kustomize edit set image controller=${IMG} && kustomize edit set namespace ${NAMESPACE}
       - cd config/default && kustomize edit set namespace ${NAMESPACE}
       - make deploy
+
+  gen-yamls:
+    vars:
+      Name: kloudlite-operator
+    env:
+      IMG: harbor.dev.madhouselabs.io/kloudlite/$ENV_NAME/{{.Name}}:latest
+      NAMESPACE: kl-core
+    cmds:
+      - make manifests
+      - |+
+        pushd config/manager > /dev/null
+        kustomize edit set image controller=${IMG}
+        kustomize edit set namespace ${NAMESPACE}
+        popd > /dev/null
+      - |+
+        pushd config/default > /dev/null
+        kustomize edit set image controller=${IMG}
+        kustomize edit set namespace ${NAMESPACE}
+        popd > /dev/null
+      - |+
+        cat config/crd/bases/*.yaml | yq -y
+
+        yamls=$(kustomize build config/default | yq 'select(.kind | [.] - ["Deployment", "Service", "ConfigMap"] | length > 0 | not)' -y)
+        echo "---"
+        echo "$yamls" | yq '
+          select((.kind == "ConfigMap") and (.metadata.name == "manager-config")) |
+          .metadata.name = "{{.Name}}-manager-config"
+        ' -y
+
+        echo "---"
+        echo "$yamls" | yq '
+          select(.kind == "Service") |
+            .metadata.labels."control-plane" = "{{.Name}}" |
+            .spec.selector."control-plane" = "{{.Name}}" |
+            .metadata.name = "{{.Name}}"
+        ' -y
+        echo "---"
+        echo "$yamls" | yq '
+          select(.kind == "Deployment") |
+            .metadata.name = "{{.Name}}" |
+            .metadata.labels."control-plane" = "{{.Name}}" |
+            .spec.selector.matchLabels."control-plane" = "{{.Name}}" |
+            .spec.template.metadata.labels."control-plane" = "{{.Name}}"
+        ' -y
 
   deploy:prod:
     vars:
@@ -140,6 +184,7 @@ tasks:
       Name: kloudlite-operator
     env:
 #       IMG: harbor.dev.madhouselabs.io/dev-kloudlite/{{.Name}}:latest
+#      IMG: harbor.dev.madhouselabs.io/kloudlite/{{.EnvName}}/{{.Name}}:latest
       IMG: harbor.dev.madhouselabs.io/kloudlite/$ENV_NAME/{{.Name}}:latest
       NAMESPACE: kl-core
     cmds:
@@ -177,13 +222,25 @@ tasks:
             .spec.selector.matchLabels."control-plane" = "{{.Name}}" |
             .spec.template.metadata.labels."control-plane" = "{{.Name}}"
         ' -y
+        
+  verify-vars:
+    silent: true
+    cmds:
+      - |+
+        [ -z "{{.Value}}" ] && echo "env-var {{.Name}} is required" && exit 1
+        exit 0
+      -
 
-  deploy:build:
+  build:
     env:
 #       IMG: harbor.dev.madhouselabs.io/kloudlite/{{.Mode}}/kloudlite-operator:latest
-      IMG: harbor.dev.madhouselabs.io/dev-kloudlite/kloudlite-operator:latest
+      IMG: harbor.dev.madhouselabs.io/kloudlite/{{.EnvName}}/kloudlite-operator:latest
       NAMESPACE: kl-core
     cmds:
+      - task: verify-vars
+        vars:
+          Name: "EnvName"
+          Value: "{{.EnvName}}"
       - make dev-docker-build dev-docker-push
 
   pre:
